import { describe, it, before, after } from "node:test";
import assert from "node:assert/strict";
import { mkdtempSync, readFileSync, rmSync, existsSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import {
  PT_TABLE_TYPE_NAMES,
  writePortableTextTableArtifacts,
} from "../src/pt-table.ts";
import { createSchemaPathPlanner } from "../src/layout.ts";
import { writePageBuilderArtifacts } from "../src/pagebuilder.ts";
import { RESERVED_SANITY_TYPE_NAMES, resolveSanityTypeNames } from "../src/naming.ts";
import { sanitizeSchemaTypes } from "../src/sanitize.ts";
import { mapDialog } from "../src/mapper.ts";
import { emitSchemaFile } from "../src/emitter.ts";
import type { DialogNode } from "aem-to-sanity-core";

/**
 * The canonical Portable Text table types (Sanity ≥ 6.6): emitted with the
 * generated schemas, reserved against AEM component names, kept out of the
 * page-builder palette, and referenced by every richtext field's `of[]`.
 */

let dir: string;
before(() => {
  dir = mkdtempSync(join(tmpdir(), "pt-table-"));
});
after(() => {
  rmSync(dir, { recursive: true, force: true });
});

describe("writePortableTextTableArtifacts", () => {
  it("writes cell.ts, row.ts, table.ts with the GENERATED banner and matching exports", async () => {
    const { files } = await writePortableTextTableArtifacts({ schemasDir: dir });
    assert.equal(files.length, 3);
    for (const name of PT_TABLE_TYPE_NAMES) {
      const file = join(dir, `${name}.ts`);
      assert.ok(existsSync(file), `${name}.ts exists`);
      const src = readFileSync(file, "utf8");
      assert.ok(
        src.startsWith("// GENERATED by aem-to-sanity-schema"),
        `${name}.ts carries the pruner-recognized banner`,
      );
      assert.match(src, new RegExp(`export const ${name} = defineType\\(`));
      assert.match(src, new RegExp(`name: "${name}"`));
    }
  });

  it("kind layout places the table types under objects/", async () => {
    const kindDir = mkdtempSync(join(tmpdir(), "pt-table-kind-"));
    try {
      const { files } = await writePortableTextTableArtifacts({
        schemasDir: kindDir,
        planner: createSchemaPathPlanner({ layout: "kind" }),
      });
      for (const name of PT_TABLE_TYPE_NAMES) {
        assert.ok(files.includes(join(kindDir, "objects", `${name}.ts`)));
        assert.ok(existsSync(join(kindDir, "objects", `${name}.ts`)));
      }
    } finally {
      rmSync(kindDir, { recursive: true, force: true });
    }
  });

  it("declares headerRows on the table type (required by the Studio plugin)", async () => {
    await writePortableTextTableArtifacts({ schemasDir: dir });
    const src = readFileSync(join(dir, "table.ts"), "utf8");
    assert.match(src, /name: "headerRows"/);
    assert.match(src, /name: "rows"/);
    assert.match(src, /type: "row"/);
  });
});

describe("page builder keeps table types out of the palette", () => {
  it("excludes cell/row/table from pageBuilder.of[] even when scanned from filenames", async () => {
    const pb = await writePageBuilderArtifacts({
      schemasDir: dir,
      componentTypeNames: ["promo", ...PT_TABLE_TYPE_NAMES],
    });
    assert.deepEqual(pb.registered, ["promo"]);
    const src = readFileSync(pb.pageBuilderFile, "utf8");
    assert.doesNotMatch(src, /type: "table"/);
  });
});

describe("naming: canonical table types are reserved", () => {
  it("includes table, row, and cell in RESERVED_SANITY_TYPE_NAMES", () => {
    for (const name of PT_TABLE_TYPE_NAMES) {
      assert.ok(RESERVED_SANITY_TYPE_NAMES.has(name), `${name} is reserved`);
    }
  });

  it("renames an AEM component named table to aemTable", () => {
    const names = resolveSanityTypeNames(["/apps/uxp/components/table"]);
    assert.equal(names.get("/apps/uxp/components/table"), "aemTable");
  });

  it("hard-errors on an explicit override claiming a reserved table name", () => {
    assert.throws(() =>
      resolveSanityTypeNames(["/apps/x/components/grid"], {
        overrides: new Map([["/apps/x/components/grid", "table"]]),
      }),
    );
  });

  it("sanitizeSchemaTypes leaves the toolkit table types alone but still renames built-ins", () => {
    const types = sanitizeSchemaTypes([
      { name: "table", type: "object", fields: [{ name: "headerRows" }] },
      { name: "row", type: "object", fields: [{ name: "cells" }] },
      { name: "cell", type: "object", fields: [{ name: "value" }] },
      { name: "image", type: "object", fields: [{ name: "x" }] },
    ] as Array<{ name: string }>);
    assert.deepEqual(
      types.map((t) => t.name),
      ["table", "row", "cell", "aemImage"],
    );
  });
});

describe("emitter: richtext fields admit table blocks", () => {
  function richtextDialog(): DialogNode {
    return {
      "sling:resourceType": "cq/gui/components/authoring/dialog",
      items: {
        text: {
          "jcr:primaryType": "nt:unstructured",
          name: "./text",
          "sling:resourceType":
            "granite/ui/components/coral/foundation/form/richtext",
        },
      },
    } as unknown as DialogNode;
  }

  it('emits of: [{ type: "block" }, { type: "table" }] for array-of-blocks', async () => {
    const noFetch = async () => {
      throw new Error("unexpected fetcher call");
    };
    const { fields, groups } = await mapDialog(richtextDialog(), noFetch);
    const src = await emitSchemaFile({
      typeName: "testRichtext",
      sourcePath: "/apps/test/richtext",
      fields,
      groups,
    });
    assert.match(src, /of: \[\{ type: "block" \}, \{ type: "table" \}\]/);
  });
});
