import { join } from "node:path";
import { writeTextFile } from "aem-to-sanity-core";
import { CONTENT_FRAGMENT_TYPE_NAMES } from "./naming.ts";

/**
 * Toolkit-owned escape hatch for Sanity's hard 20-level attribute-depth
 * limit. When a page's preserved container nesting (tabs-in-tabs, panels,
 * wrappers) would exceed the limit, `aem-transform` cuts the deepest
 * subtree into a standalone `contentFragment` document — depth is counted
 * per document, so the budget resets at the cut — and leaves a
 * `contentFragmentRef` block in its place. Both types are emitted as
 * generated schemas on every run (same distribution mechanism as the
 * Portable Text table types) and reserved in `naming.ts` so an AEM
 * component can't claim the names.
 */
export { CONTENT_FRAGMENT_TYPE_NAMES };

export interface WriteContentFragmentArtifactsOptions {
  /** Directory where generated schema .ts files are written. */
  schemasDir: string;
  /** Page-builder array type the fragment's `content` field reuses. */
  pageBuilderTypeName: string;
}

export interface WriteContentFragmentArtifactsResult {
  /** Absolute paths of the emitted files. */
  files: string[];
}

const BANNER = `// GENERATED by aem-to-sanity-schema. Do not edit by hand.
// Escape hatch for Sanity's 20-level attribute-depth limit: aem-transform
// cuts subtrees that would exceed the limit into contentFragment documents
// and leaves a contentFragmentRef block in the parent's builder array.`;

function contentFragmentSource(pageBuilderTypeName: string): string {
  return `${BANNER}
import { defineField, defineType } from "sanity";

export const contentFragment = defineType({
  name: "contentFragment",
  title: "Content fragment",
  type: "document",
  fields: [
    defineField({ name: "title", title: "Title", type: "string" }),
    defineField({
      name: "content",
      title: "Content",
      type: ${JSON.stringify(pageBuilderTypeName)},
    }),
  ],
});
`;
}

const CONTENT_FRAGMENT_REF_SOURCE = `${BANNER}
import { defineField, defineType } from "sanity";

export const contentFragmentRef = defineType({
  name: "contentFragmentRef",
  title: "Content fragment",
  type: "object",
  fields: [
    defineField({
      name: "fragment",
      title: "Fragment",
      type: "reference",
      to: [{ type: "contentFragment" }],
    }),
  ],
});
`;

export async function writeContentFragmentArtifacts(
  opts: WriteContentFragmentArtifactsOptions,
): Promise<WriteContentFragmentArtifactsResult> {
  const files: string[] = [];
  const fragmentFile = join(opts.schemasDir, "contentFragment.ts");
  await writeTextFile(fragmentFile, contentFragmentSource(opts.pageBuilderTypeName));
  files.push(fragmentFile);
  const refFile = join(opts.schemasDir, "contentFragmentRef.ts");
  await writeTextFile(refFile, CONTENT_FRAGMENT_REF_SOURCE);
  files.push(refFile);
  return { files };
}
