import { readFile } from "node:fs/promises";
import { join } from "node:path";
import { writeTextFile, type Logger } from "aem-to-sanity-core";
import { toTitleCase } from "./naming.ts";
import { PT_TABLE_TYPE_NAMES } from "./pt-table.ts";
import {
  FLAT_PLANNER,
  scanGeneratedSchemaFiles,
  type SchemaPathPlanner,
} from "./layout.ts";

const GENERATED_MARKER = "GENERATED by aem-to-sanity-schema pagebuilder";

export interface PageBuilderMember {
  /** Sanity type name, matches the emitted `defineType.name`. */
  name: string;
  /** Friendly label rendered in Page Builder rows and the "+ Add" menu. */
  title: string;
}

export interface WritePageBuilderArtifactsOptions {
  /** Directory where schema .ts files (including page.ts / pageBuilder.ts) are written. */
  schemasDir: string;
  /**
   * Block-type names to include in `pageBuilder.of[]`. Each entry becomes a
   * `defineArrayMember({ type, title })` so the Page Builder always renders
   * the component's friendly title on array rows — even when a row's data is
   * empty. When a caller knows the friendly titles (the main migration
   * pipeline does), pass {@link componentMembers} instead to avoid the
   * `toTitleCase` fallback.
   */
  componentTypeNames?: string[];
  /** Pre-resolved `{name, title}` pairs. Takes precedence over `componentTypeNames`. */
  componentMembers?: PageBuilderMember[];
  /** Names to exclude from `pageBuilder.of[]` (e.g. page-level components that shouldn't nest inside a page). */
  exclude?: string[];
  /** Name of the generated page document type. Default: "page". */
  pageTypeName?: string;
  /** Name of the generated page-builder array type. Default: "pageBuilder". */
  pageBuilderTypeName?: string;
  /** Layout planner deciding subfolder placement. Default: flat. */
  planner?: SchemaPathPlanner;
  logger?: Logger;
}

export interface WritePageBuilderArtifactsResult {
  pageFile: string;
  pageBuilderFile: string;
  /** False if a hand-authored `page.ts` was found and preserved. */
  pageWritten: boolean;
  /** Type names registered in `pageBuilder.of[]`. */
  registered: string[];
}

export async function writePageBuilderArtifacts(
  opts: WritePageBuilderArtifactsOptions,
): Promise<WritePageBuilderArtifactsResult> {
  const {
    schemasDir,
    componentTypeNames,
    componentMembers,
    exclude = [],
    pageTypeName = "page",
    pageBuilderTypeName = "pageBuilder",
    planner = FLAT_PLANNER,
    logger,
  } = opts;

  // Portable Text table types are block-level members inside richtext
  // fields, not page-body components — keep them out of the "+ Add" menu.
  // Same for the `contentFragment` DOCUMENT type (its `contentFragmentRef`
  // block IS a palette member). Baked in here (not per-caller) so the
  // filename-scanning CLI entry point is covered too.
  const excludeSet = new Set([
    ...exclude,
    ...PT_TABLE_TYPE_NAMES,
    "contentFragment",
    pageTypeName,
    pageBuilderTypeName,
  ]);

  // Prefer pre-resolved members (names + friendly titles). Fall back to
  // title-casing the type name when only names are provided — the CLI entry
  // point works off on-disk filenames and has no other way to know titles.
  const sourceMembers: PageBuilderMember[] =
    componentMembers && componentMembers.length > 0
      ? componentMembers
      : (componentTypeNames ?? []).map((name) => ({
          name,
          title: toTitleCase(name),
        }));

  const seen = new Set<string>();
  const registeredMembers = sourceMembers
    .filter((m) => {
      if (excludeSet.has(m.name) || seen.has(m.name)) return false;
      seen.add(m.name);
      return true;
    })
    .sort((a, b) => a.name.localeCompare(b.name));
  const registered = registeredMembers.map((m) => m.name);

  // The page-builder array is not a document; it folders with the objects.
  const pageBuilderFile = join(
    schemasDir,
    planner.relPath(pageBuilderTypeName, "object"),
  );
  const pageFile = join(schemasDir, planner.relPath(pageTypeName, "document"));

  await writeTextFile(
    pageBuilderFile,
    renderPageBuilder(pageBuilderTypeName, registeredMembers),
  );

  const pageWritten = await maybeWritePage(pageFile, pageTypeName, pageBuilderTypeName, logger);

  return { pageFile, pageBuilderFile, pageWritten, registered };
}

function renderPageBuilder(
  typeName: string,
  members: PageBuilderMember[],
): string {
  const rendered = members
    .map(
      (m) =>
        `    defineArrayMember({ type: ${JSON.stringify(m.name)}, title: ${JSON.stringify(m.title)} }),`,
    )
    .join("\n");
  return `// ${GENERATED_MARKER}. Do not edit by hand.
// Regenerated on every migration run; add or remove members by running:
//   pnpm aem-to-sanity-pagebuilder --output-dir <dir>
import { defineArrayMember, defineType } from "sanity";

export const ${typeName} = defineType({
  name: ${JSON.stringify(typeName)},
  type: "array",
  of: [
${rendered}
  ],
});
`;
}

function renderPage(pageTypeName: string, pageBuilderTypeName: string): string {
  return `// ${GENERATED_MARKER}. Safe to delete or replace.
// To author a custom page schema, remove this file (or the marker comment) — the
// migration will not overwrite it. Custom page types can still reference the
// generated ${pageBuilderTypeName} array.
import { defineField, defineType } from "sanity";

export const ${pageTypeName} = defineType({
  name: ${JSON.stringify(pageTypeName)},
  title: "Page",
  type: "document",
  preview: {
    select: {
      title: "title",
      slug: "slug.current",
    },
    prepare({ title, slug }) {
      return {
        title: typeof title === "string" && title.trim() ? title.trim() : "Untitled page",
        subtitle:
          typeof slug === "string" && slug.trim() ? "/" + slug.trim() : undefined,
      };
    },
  },
  fields: [
    defineField({ name: "title", type: "string", validation: (r) => r.required() }),
    defineField({
      name: "slug",
      type: "slug",
      options: { source: "title", maxLength: 96 },
      validation: (r) => r.required(),
    }),
    // Lifted from AEM \`jcr:content/cq:tags\` by \`aem-transform\` and resolved
    // through the categories manifest from \`aem-tags\`. Remove this field if
    // the migration source has no page-level tags.
    defineField({
      name: "tags",
      type: "array",
      of: [{ type: "reference", to: [{ type: "category" }] }],
    }),
    defineField({ name: ${JSON.stringify(pageBuilderTypeName)}, type: ${JSON.stringify(pageBuilderTypeName)} }),
  ],
});
`;
}

async function maybeWritePage(
  pageFile: string,
  pageTypeName: string,
  pageBuilderTypeName: string,
  logger: Logger | undefined,
): Promise<boolean> {
  let existing: string | undefined;
  try {
    existing = await readFile(pageFile, "utf8");
  } catch (err) {
    if ((err as NodeJS.ErrnoException).code !== "ENOENT") throw err;
  }

  if (existing !== undefined && !existing.includes(GENERATED_MARKER)) {
    logger?.info(
      `pagebuilder: preserving hand-authored ${pageFile} (no GENERATED marker found)`,
    );
    return false;
  }

  await writeTextFile(pageFile, renderPage(pageTypeName, pageBuilderTypeName));
  return true;
}

/**
 * Scan a schemas directory (recursively — subfolder layouts included) for
 * emitted type files. Returns the list of Sanity type names: the
 * `defineType({ name })` declared inside each file when readable, falling
 * back to the file basename (the emitter convention — basename == type name
 * except in the `file` suffix mode, where `accordionType.ts` declares
 * `name: "accordion"`). The root `index.ts`, the page type, and the
 * page-builder type are excluded from the result.
 */
export async function scanSchemaTypeNames(
  schemasDir: string,
  exclude: string[] = ["page", "pageBuilder"],
): Promise<string[]> {
  const files = await scanGeneratedSchemaFiles(schemasDir);
  const excludeSet = new Set(exclude);
  const names = await Promise.all(
    files.map(async (f) => {
      try {
        const contents = await readFile(join(schemasDir, f.relPath), "utf8");
        const m = contents.match(
          /defineType\(\{\s*name:\s*"([A-Za-z][A-Za-z0-9_]*)"/,
        );
        if (m) return m[1]!;
      } catch {
        // unreadable file — the basename is the best remaining guess
      }
      return f.typeName;
    }),
  );
  return names.filter((n) => !excludeSet.has(n));
}

/**
 * Rewrite `{schemasDir}/index.ts` from scanned files, placing `pageBuilder`
 * and `page` last so `allSchemaTypes` is usable as a single array plug-in to
 * `defineConfig({ schema: { types } })`. Import specifiers carry the file's
 * path relative to the schemas dir (POSIX separators), so subfolder layouts
 * resolve without any change on the Studio side — the barrel itself always
 * stays at the root.
 */
export async function rewriteBarrelFromDisk(
  schemasDir: string,
  pageTypeName = "page",
  pageBuilderTypeName = "pageBuilder",
): Promise<string> {
  const scanned = await scanGeneratedSchemaFiles(schemasDir);
  const relPathByName = new Map(scanned.map((f) => [f.typeName, f.relPath]));
  const components = scanned
    .map((f) => f.typeName)
    .filter((n) => n !== pageTypeName && n !== pageBuilderTypeName);
  const allNames = [...components, pageBuilderTypeName, pageTypeName];
  const imports = allNames
    .map((n) => `import { ${n} } from "./${relPathByName.get(n) ?? `${n}.ts`}";`)
    .join("\n");
  const src = `// GENERATED by aem-to-sanity-schema. Do not edit by hand.
${imports}

export const allSchemaTypes = [${allNames.join(", ")}];
${allNames.map((n) => `export { ${n} };`).join("\n")}
`;
  const file = join(schemasDir, "index.ts");
  await writeTextFile(file, src);
  return file;
}
