import { join } from "node:path";
import { writeTextFile } from "aem-to-sanity-core";
import { PORTABLE_TEXT_TABLE_TYPE_NAMES } from "./naming.ts";
import { FLAT_PLANNER, type SchemaPathPlanner } from "./layout.ts";

/**
 * Canonical type names claimed by Sanity's native Portable Text table
 * feature (Studio ≥ 6.6): a `table` object whose `rows` hold `row` objects,
 * whose `cells` hold `cell` objects with a `value` block array. The Studio's
 * table plugin binds to these names by default (no `containers` remapping
 * needed), so the migrator emits them as toolkit-owned generated types and
 * `naming.ts` reserves them — an AEM component that would derive one of
 * these names gets the `aem` prefix instead (e.g. `aemTable`).
 */
export const PT_TABLE_TYPE_NAMES = PORTABLE_TEXT_TABLE_TYPE_NAMES;

export interface WritePortableTextTableArtifactsOptions {
  /** Directory where generated schema .ts files are written. */
  schemasDir: string;
  /** Layout planner deciding subfolder placement. Default: flat. */
  planner?: SchemaPathPlanner;
}

export interface WritePortableTextTableArtifactsResult {
  /** Absolute paths of the emitted files (cell.ts, row.ts, table.ts). */
  files: string[];
}

const BANNER = `// GENERATED by aem-to-sanity-schema. Do not edit by hand.
// Canonical table shape for Sanity's native Portable Text tables (Studio ≥ 6.6):
// table → rows[] → cells[] → value (block array). Emitted on every schema run
// so richtext fields (\`of: [{ type: "block" }, { type: "table" }]\`) resolve.`;

const FILE_SOURCES: Record<(typeof PT_TABLE_TYPE_NAMES)[number], string> = {
  cell: `${BANNER}
import { defineField, defineType } from "sanity";

export const cell = defineType({
  name: "cell",
  title: "Table cell",
  type: "object",
  fields: [
    defineField({
      name: "value",
      title: "Content",
      type: "array",
      of: [{ type: "block" }],
    }),
  ],
});
`,
  row: `${BANNER}
import { defineField, defineType } from "sanity";

export const row = defineType({
  name: "row",
  title: "Table row",
  type: "object",
  fields: [
    defineField({
      name: "cells",
      title: "Cells",
      type: "array",
      of: [{ type: "cell" }],
    }),
  ],
});
`,
  table: `${BANNER}
import { defineField, defineType } from "sanity";

export const table = defineType({
  name: "table",
  title: "Table",
  type: "object",
  fields: [
    // Required by the Studio table plugin: fields the schema doesn't declare
    // are stripped on save, so without this the header-row toggle silently
    // does nothing.
    defineField({ name: "headerRows", title: "Header rows", type: "number" }),
    defineField({
      name: "rows",
      title: "Rows",
      type: "array",
      of: [{ type: "row" }],
    }),
  ],
});
`,
};

/**
 * Write the three canonical table schema files into the generated schemas
 * directory. Distributing them through the generated barrel (instead of a
 * hand-registered export from `aem-to-sanity-studio`) means every operator —
 * including existing tenants whose `schemas/index.ts` is never rewritten by
 * `studio:sync` — picks them up on the next `migrate:schema` run with zero
 * manual steps.
 */
export async function writePortableTextTableArtifacts(
  opts: WritePortableTextTableArtifactsOptions,
): Promise<WritePortableTextTableArtifactsResult> {
  const planner = opts.planner ?? FLAT_PLANNER;
  const files: string[] = [];
  for (const name of PT_TABLE_TYPE_NAMES) {
    const file = join(opts.schemasDir, planner.relPath(name, "object"));
    await writeTextFile(file, FILE_SOURCES[name]);
    files.push(file);
  }
  return { files };
}
